package mil.nga.giat.mage.sdk.datastore.user;

import java.io.Serializable;

public enum Permission implements Serializable {
    CREATE_DEVICE,
    CREATE_EVENT,
    CREATE_FEATURE,
    CREATE_LAYER,
    CREATE_LOCATION,
    CREATE_ROLE,
    CREATE_TEAM,
    CREATE_USER,
    DELETE_DEVICE,
    DELETE_EVENT,
    DELETE_FEATURE,
    DELETE_LAYER,
    DELETE_LOCATION,
    DELETE_ROLE,
    DELETE_TEAM,
    DELETE_USER,
    READ_DEVICE,
    READ_EVENT,
    READ_FEATURE,
    READ_LAYER,
    READ_LOCATION,
    READ_ROLE,
    READ_TEAM,
    READ_USER,
    UPDATE_DEVICE,
    UPDATE_EVENT,
    UPDATE_FEATURE,
    UPDATE_LAYER,
    UPDATE_LOCATION,
    UPDATE_ROLE,
    UPDATE_TEAM,
    UPDATE_USER;
}
